# -*- coding: utf-8 -*-
"""train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YH8wyAI0JArM7Nv--dDVshKAmiFIEAFn
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
import joblib

# Load dataset
df = pd.read_csv("/content/credit_card_fraud_synthetic.csv")

# Target
y = df["Class"]

# Features
X = df.drop(columns=["Class"])

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=21, stratify=y
)

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight="balanced"
)

# Train
model.fit(X_train, y_train)

# Evaluate
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

# Save model
joblib.dump(model, "fraud_model.pkl")

# Save feature order (VERY IMPORTANT)
joblib.dump(list(X.columns), "feature_names.pkl")

df_class_1 = df[df['Class'] == 1]
print(df_class_1)

df_class_1.to_csv('df_class_1.csv', index=False)

